### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mbret** [fread-ink/epub-cfi-resolver#6]
Would you be interested in supporting typescript ?

**Comment by Juul** [comment]
I'm not sure what you mean by that?

**Comment by mbret** [comment]
Basically either writing the code in typescript or providing a typedef

**Comment by Juul** [comment]
If there is a way to add this type information in some extra file that doesn't add any typescript to the existing code then that would be fine. If you're talking about adding turning this project into something that has to be "compiled" from typescript to javascript in order to run in a browser then I'm not interested.
